### ISSUE TITLE
[Bug]: Placing cells at rapidly differing positions causes performance issues.

### ISSUE THREAD

**Issue by ProjectHSI** [Voxelstice/a-destruction-game#2]
### Game version

0.0.2a

### Operating system

Windows - 22H2 - 19045.4355 - Windows Feature Experience Pack 1000.19056.1000.0

### Bug Information

If you start placing a cell and move the mouse fast, the game slows down.

### Reproduction Steps

1. Start placing cells.
2. Move the mouse around.

### Log file

Nothing in the logs applies to this issue.

### _

- [X] I have updated to the latest version to make sure my bug hasnt been fixed.

**Comment by Voxelstice** [comment]
Known issue, it's really due to the way i handle the falling sand sim

**Comment by Voxelstice** [comment]
Should be fixed within next release, made buffer swapping only do its thing in the update step
