### ISSUE TITLE
[Bug]: OpenGL buffer is cleared twice for no reason

### ISSUE THREAD

**Issue by ProjectHSI** [Voxelstice/a-destruction-game#3]
### Game version

0.0.2a

### Operating system

Windows - 22H2 - 19045.4355 - Windows Feature Experience Pack 1000.19056.1000.0

### Bug Information

The OpenGL buffer is cleared twice, clearing it twice is wasteful.

Intended Behaviour: OpenGL buffer is cleared once, which is the minimum amount needed for safety.

this will save 60 microseconds on your game
<img width="664" alt="Screenshot 2024-04-27 085731" src="https://github.com/Voxelstice/lightship/assets/57279339/0976e61d-faf6-4d8d-89ea-b8db8e5bb8fa">

### Reproduction Steps

1. Use Nvidia NSight Graphics

### Log file

The log file does not apply to this.

### _

- [X] I have updated to the latest version to make sure my bug hasnt been fixed.

**Comment by Voxelstice** [comment]
indeed was clearing twice, it has since been fixed internally
