### ISSUE TITLE
[Bug]: Program doesn't catch CTRL+C

### ISSUE THREAD

**Issue by ProjectHSI** [Voxelstice/a-destruction-game#4]
### Game version

0.0.2a

### Operating system

Windows - 22H2 - 19045.4355 - Windows Feature Experience Pack 1000.19056.1000.0

### Bug Information

The program should not halt on Ctrl+C

### Reproduction Steps

1. Press CTRL+C on the console window that is created.

### Log file

Program does NOT exit properly

### _

- [X] I have updated to the latest version to make sure my bug hasnt been fixed.

**Comment by Voxelstice** [comment]
the console window isn't actually supposed to be there in release, i have a pragma comment linker line on the very top of the main.cpp file that since was commented out for various reasons i can't get on top of my mind, will not be fixing at the moment
